Repository ubsuny/23-Homework5G1, pull requests merged in 2023-11, with the labels that each got.

#17 Station data, Sand Island, Midway, United States (MID)
  sand_island_data.txt
  station_data.ipynb
Labels: processing, Update, algorithm

#24 License (Apache 2.0)
  LICENSE
Labels: enhancement

#36 Create calculate_frequency.py
  calculate_frequency.py
Labels: enhancement, finalize, PendingReview, Highlights, algorithm
